### ISSUE TITLE
unusable in tests

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-bankai#5]
watch mode is always enabled, but this will cause the process to hang during tests and wait.
Passing `watch: false`  as an options solves it.

Maybe we should have that set as a default, and accept `watch: true`. This would be the reverse to what bankai does.

**Comment by delvedor** [comment]
Nice catch, now I understood why I had to put [this](https://github.com/fastify/fastify-pigeon/blob/master/test.js#L102) at the end of the test.
I agree with you that `watch` by default must be `false` for a better usability in our context.

@yoshuawuyts just out of curiosity, why in bankai `watch` is `true` by default?

**Comment by yoshuawuyts** [comment]
Err, felt it made sense to have it watch by default - main use case for was
recompiling and serving assets; not having it watch would probably feel a
bit weird haha

**Comment by mcollina** [comment]
@yoshuawuyts what would be the dev workflow with bankai, related to moving the generated stuff to prod?

**Comment by yoshuawuyts** [comment]
Generally I use bankai from the CLI and upload it to nginx somehow - if I
were to run it on a server directly I'd probably turn off live reload, and
let nginx + CDNs take care of it. Hope this makes sense?
